<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Arr;

class FacultyMemberFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $staff = [
            [
                'name' => 'Dr. Ossama El-Nahhas',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(19).png',
                'title' => 'Head of Information Technology Department',
                'sub_title' => 'Associate Professor',
                'head_description' => 'Dr. Ossama El-Nahhas leads the Information Technology Department, overseeing academic programs and research initiatives.',
                'career' => 'Dr. El-Nahhas has a distinguished career in academia and industry, with expertise in software engineering and artificial intelligence.',
                'scientific_interests' => 'His scientific interests include machine learning, natural language processing, and computer vision.',
                'experience' => 'He has over 15 years of experience in teaching and research, collaborating with leading institutions and publishing in top-tier journals and conferences.',
                'word' => 'Dr. El-Nahhas is committed to promoting excellence in education and research, preparing students for successful careers in the rapidly evolving field of information technology.',
                'certificates_title' => 'Ph.D. in Computer Science',
                'certificates_description' => 'Dr. El-Nahhas holds a Ph.D. in Computer Science from a prestigious university, with his research focusing on machine learning algorithms for text classification.',
                'email' => 'ossama@example.com',
                'cv' => 'https://example.com/cv/ossama_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Advancements in Deep Learning for Natural Language Processing", Journal of Artificial Intelligence, 2020.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Nihal Al-Azli',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(18).png',
                'title' => 'Vice Head of Information Technology Department',
                'sub_title' => 'Assistant Professor',
                'head_description' => 'Dr. Nihal Al-Azli serves as the Vice Head of the Information Technology Department, supporting departmental activities and initiatives.',
                'career' => 'Dr. Al-Azli has a diverse career background, with experience in academia, research, and industry.',
                'scientific_interests' => 'Her scientific interests include cybersecurity, data privacy, and cloud computing.',
                'experience' => 'She has worked on numerous research projects and has industry experience in cybersecurity consulting for multinational corporations.',
                'word' => 'Dr. Al-Azli is dedicated to fostering a collaborative and innovative environment within the department, nurturing the next generation of IT professionals.',
                'certificates_title' => 'Ph.D. in Information Security',
                'certificates_description' => 'Dr. Al-Azli holds a Ph.D. in Information Security and has received certifications in cybersecurity from leading institutions.',
                'email' => 'nihal@example.com',
                'cv' => 'https://example.com/cv/nihal_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Privacy-Preserving Techniques for Data Sharing in Cloud Environments", IEEE Transactions on Dependable and Secure Computing, 2019.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Ashraf Abdel Aziz',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(17).png',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Ashraf Abdel Aziz leads the department with a focus on academic excellence and research advancement.',
                'career' => 'Dr. Abdel Aziz has a distinguished career in academia, spanning over two decades.',
                'scientific_interests' => 'His scientific interests include artificial intelligence, machine learning, and data mining.',
                'experience' => 'He has extensive experience in teaching, research supervision, and academic administration.',
                'word' => 'Dr. Abdel Aziz is committed to fostering an environment of innovation and collaboration within the department, preparing students to become future leaders in their field.',
                'certificates_title' => 'Ph.D. in Computer Science',
                'certificates_description' => 'Dr. Abdel Aziz holds a Ph.D. in Computer Science from a reputable university, with a focus on machine learning algorithms.',
                'email' => 'ashraf@example.com',
                'cv' => 'https://example.com/cv/ashraf_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Advancements in Deep Learning for Image Recognition", IEEE Transactions on Pattern Analysis and Machine Intelligence, 2021.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Mohamed Ahmed',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(10).jpg',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Mohamed Ahmed leads the Health Informatics Technology Department, overseeing academic programs and research initiatives in health informatics and data management.',
                'career' => 'Dr. Ahmed has a diverse background in academia, industry, and research, with expertise in health informatics, data analytics, and electronic health records.',
                'scientific_interests' => 'His scientific interests include health data interoperability, clinical decision support systems, and telehealth technologies.',
                'experience' => 'He has served as a consultant for healthcare organizations and has led research projects funded by national and international agencies.',
                'word' => 'Dr. Ahmed is passionate about leveraging technology to improve healthcare delivery and patient outcomes, driving innovation in health informatics education and research.',
                'certificates_title' => 'Ph.D. in Health Informatics',
                'certificates_description' => 'Dr. Ahmed holds a Ph.D. in Health Informatics from a prestigious institution, with his research focusing on interoperability standards for health information exchange.',
                'email' => 'mohamed@example.com',
                'cv' => 'https://example.com/cv/mohamed_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Developing Standards-Based Frameworks for Health Information Exchange", Journal of Medical Systems, 2020.',
                'user_id' => 1,
                'department_id' => 9,
                'faculty_id' => 2,
            ],
            [
                'name' => 'Dr. Eman Shawqi',
                'image' => 'https://th.bing.com/th/id/R.068a89f2d286a56cc99bc51b7c655b3b?rik=agsMS3PttzVqkQ&pid=ImgRaw&r=0',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Eman Shawqi is an Assistant Professor in the Department of Pharmaceutical Technology, specializing in pharmaceutical formulation and drug delivery.',
                'career' => 'She has a rich academic background and research experience, contributing significantly to the field of pharmaceutical technology.',
                'scientific_interests' => 'Her scientific interests include nanostructured drug delivery systems, controlled release formulations, and novel drug delivery approaches.',
                'experience' => 'Dr. Shawqi has published several research papers in reputed journals and has participated in research projects focusing on developing innovative drug delivery technologies.',
                'word' => 'She is committed to educating and mentoring students, preparing them to become future leaders in the pharmaceutical industry.',
                'certificates_title' => 'Ph.D. in Pharmaceutical Sciences',
                'certificates_description' => 'Dr. Shawqi holds a Ph.D. in Pharmaceutical Sciences from a prestigious institution, with her doctoral research focusing on nanotechnology-based drug delivery systems.',
                'email' => 'eman@example.com',
                'cv' => 'https://example.com/cv/eman_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Development of Lipid-Based Nanocarriers for Targeted Drug Delivery", International Journal of Pharmaceutics, 2020.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Mohamed Abd-Elfatah',
                'image' => 'https://th.bing.com/th/id/R.068a89f2d286a56cc99bc51b7c655b3b?rik=agsMS3PttzVqkQ&pid=ImgRaw&r=0',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Mohamed Abd-Elfatah is an Associate Professor in the Department of Pharmaceutical Technology, specializing in pharmaceutical analysis and quality control.',
                'career' => 'He has a distinguished academic career and extensive experience in pharmaceutical research, particularly in the areas of drug analysis and quality assurance.',
                'scientific_interests' => 'His scientific interests include analytical method development, validation, and pharmacopoeial compliance.',
                'experience' => 'Dr. Abd-Elfatah has authored numerous research articles and book chapters on pharmaceutical analysis and quality control, contributing to the advancement of the field.',
                'word' => 'He is dedicated to promoting excellence in pharmaceutical education and research, fostering a culture of quality and compliance in the pharmaceutical industry.',
                'certificates_title' => 'Ph.D. in Pharmaceutical Sciences',
                'certificates_description' => 'Dr. Abd-Elfatah earned his Ph.D. in Pharmaceutical Sciences with a focus on analytical chemistry and pharmaceutical quality control.',
                'email' => 'mohamed@example.com',
                'cv' => 'https://example.com/cv/mohamed_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Development and Validation of Analytical Methods for Pharmaceutical Analysis", Journal of Pharmaceutical and Biomedical Analysis, 2019.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Mohamed El-Shazly',
                'image' => 'https://th.bing.com/th/id/R.068a89f2d286a56cc99bc51b7c655b3b?rik=agsMS3PttzVqkQ&pid=ImgRaw&r=0',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Mohamed El-Shazly is an Associate Professor in the Department of Pharmaceutical Technology, specializing in pharmaceutical biotechnology and pharmacogenomics.',
                'career' => 'He has a diverse academic background and extensive research experience in pharmaceutical biotechnology, with a focus on personalized medicine and drug discovery.',
                'scientific_interests' => 'His scientific interests include genetic variation in drug response, pharmacogenomics-guided therapy, and biopharmaceutical development.',
                'experience' => 'Dr. El-Shazly has led research projects investigating the genetic basis of drug response variability and has published research findings in leading scientific journals.',
                'word' => 'He is committed to advancing personalized medicine through innovative research and education, aiming to improve patient outcomes and drug safety.',
                'certificates_title' => 'Ph.D. in Pharmaceutical Biotechnology',
                'certificates_description' => 'Dr. El-Shazly holds a Ph.D. in Pharmaceutical Biotechnology, focusing on pharmacogenomics and personalized medicine.',
                'email' => 'mohamed@example.com',
                'cv' => 'https://example.com/cv/mohamed_cv.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Pharmacogenomics of Anticancer Drugs: Implications for Personalized Therapy", Pharmacogenomics, 2018.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Hesham',
                'image' => 'https://th.bing.com/th/id/R.068a89f2d286a56cc99bc51b7c655b3b?rik=agsMS3PttzVqkQ&pid=ImgRaw&r=0',
                'title' => 'Professor',
                'sub_title' => null ,
                'head_description' => 'Dr. Hesham is a seasoned academic professional with expertise in pharmaceutical technology. He has made significant contributions to the field through his research and teaching.',
                'career' => 'With a career spanning over two decades, Dr. Hesham has held various academic positions and has been actively involved in research projects addressing current challenges in pharmaceutical technology.',
                'scientific_interests' => 'His scientific interests include drug formulation, pharmaceutical analysis, and drug delivery systems.',
                'experience' => 'Dr. Hesham has extensive experience in teaching undergraduate and graduate courses in pharmaceutical technology. He has supervised numerous research projects and mentored students in their academic and research pursuits.',
                'word' => 'He is committed to advancing pharmaceutical education and research, preparing students to excel in the pharmaceutical industry and contribute to healthcare innovation.',
                'certificates_title' => 'Ph.D. in Pharmaceutical Technology',
                'certificates_description' => 'Dr. Hesham holds a Ph.D. in Pharmaceutical Technology from a reputable institution, with his doctoral research focusing on novel drug delivery systems.',
                'email' => 'hesham@example.com',
                'cv' => '',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Formulation and Evaluation of Controlled Release Drug Delivery Systems", Journal of Pharmaceutical Sciences, 2020.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Gasser',
                'image' => 'https://th.bing.com/th/id/R.068a89f2d286a56cc99bc51b7c655b3b?rik=agsMS3PttzVqkQ&pid=ImgRaw&r=0',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Gasser is a distinguished academician with expertise in pharmaceutical technology and drug development. He has played a pivotal role in advancing pharmaceutical education and research.',
                'career' => 'Throughout his illustrious career, Dr. Gasser has held leadership positions in academia and has contributed extensively to research projects focusing on pharmaceutical formulation and drug delivery.',
                'scientific_interests' => 'His scientific interests encompass a wide range of areas, including nanotechnology, drug targeting, and pharmacokinetics.',
                'experience' => 'Dr. Gasser brings a wealth of experience to his role, having supervised numerous graduate students and postdoctoral fellows. He has published extensively in peer-reviewed journals and has received recognition for his contributions to the field.',
                'word' => 'He is passionate about nurturing the next generation of pharmaceutical scientists and fostering collaboration between academia and industry.',
                'certificates_title' => 'Ph.D. in Pharmaceutical Sciences',
                'certificates_description' => 'Dr. Gasser earned his Ph.D. in Pharmaceutical Sciences with a focus on drug delivery systems and nanotechnology.',
                'email' => 'gasser@example.com',
                'cv' => '',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Development of Nanoparticle-Based Drug Delivery Systems for Cancer Therapy", Advanced Drug Delivery Reviews, 2019.',
                'user_id' => 1,
                'department_id' => 1,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Abeer Ahmed Mohamed Hedia',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(20).jpg',
                'title' => 'Head of TAE',
                'sub_title' => "Professor",
                'head_description' => 'Dr. Abeer Ahmed Mohamed Hedia is a highly respected academician and researcher in the field of health informatics. She has made significant contributions to the advancement of healthcare through her expertise in data management and analysis.',
                'career' => 'With over a decade of experience in academia and research, Dr. Abeer has held various leadership roles and has led interdisciplinary research teams focusing on health informatics and data science.',
                'scientific_interests' => 'Her scientific interests include health data analytics, electronic health records, and clinical informatics.',
                'experience' => 'Dr. Abeer has a proven track record of securing research funding and collaborating with healthcare organizations to address critical issues in health informatics. She has published extensively and has presented her research findings at national and international conferences.',
                'word' => 'She is committed to leveraging technology and data-driven approaches to improve healthcare outcomes and enhance patient care.',
                'certificates_title' => 'Ph.D. in Health Informatics',
                'certificates_description' => 'Dr. Abeer holds a Ph.D. in Health Informatics from a renowned institution, with her doctoral research focusing on data integration and interoperability in healthcare systems.',
                'email' => 'abeer@example.com',
                'cv' => 'https://linkdhub.github.io/batu-images/files/2024-Dr%20Abeer%20Hedia%20CV%20and%20Certifications.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Data-Driven Approaches for Predictive Modeling in Healthcare", Journal of Biomedical Informatics, 2021.',
                'user_id' => 1,
                'department_id' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Bassem Nashaat Zakher',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(19).jpg',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Bassem Nashaat Zakher is an accomplished academician with expertise in health informatics and data management. He leads the Health Informatics Department with a commitment to excellence in education and research.',
                'career' => 'Dr. Zakher has an extensive career in academia, spanning over two decades. He has held various leadership roles and has contributed significantly to the field of health informatics through his research and teaching activities.',
                'scientific_interests' => 'His scientific interests include health data analytics, electronic health records, and clinical decision support systems.',
                'experience' => 'Dr. Zakher brings a wealth of experience to his role as the department chair, having supervised numerous research projects and mentored students in their academic and research pursuits. He has published extensively in peer-reviewed journals and has presented his research findings at national and international conferences.',
                'word' => 'He is dedicated to fostering innovation in health informatics and preparing students to address the complex challenges facing the healthcare industry.',
                'certificates_title' => 'Ph.D. in Health Informatics',
                'certificates_description' => 'Dr. Zakher holds a Ph.D. in Health Informatics from a prestigious institution, with his doctoral research focusing on data integration and interoperability in healthcare systems.',
                'email' => 'bassem@example.com',
                'cv' => 'https://linkdhub.github.io/batu-images/files/Dr.%20Bassem%20Nashaat%20CV.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Data-Driven Approaches for Predictive Modeling in Healthcare", Journal of Biomedical Informatics, 2021.',
                'user_id' => 1,
                'department_id' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Amira M. Galal Darwish',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(21).jpg',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Amira M. Galal Darwish is a highly regarded academician and researcher in the field of health informatics. She serves as the Vice Chairman of the Health Informatics Department, bringing extensive expertise and leadership to her role.',
                'career' => 'With over a decade of experience in academia and research, Dr. Darwish has made significant contributions to the advancement of health informatics through her research projects and teaching activities.',
                'scientific_interests' => 'Her scientific interests encompass a wide range of areas, including health information exchange, telemedicine, and health data privacy.',
                'experience' => 'Dr. Darwish has a proven track record of securing research funding and collaborating with healthcare organizations to address critical issues in health informatics. She is committed to mentoring the next generation of health informatics professionals and fostering interdisciplinary collaboration.',
                'word' => 'She is passionate about leveraging technology to improve healthcare delivery and patient outcomes, and her work has a direct impact on shaping the future of healthcare.',
                'certificates_title' => 'Ph.D. in Health Informatics',
                'certificates_description' => 'Dr. Darwish earned her Ph.D. in Health Informatics with a focus on health information exchange and interoperability.',
                'email' => 'amira@example.com',
                'cv' => 'https://linkdhub.github.io/batu-images/files/CV-20240226-Darwish-EN.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Health Information Exchange Standards and Implementation Challenges", Journal of Medical Systems, 2020.',
                'user_id' => 1,
                'department_id' => 3,
                'faculty_id' => 1,
            ],
            [
                'name' => 'Dr. Wafaa Ahmed Shaker',
                'image' => 'https://linkdhub.github.io/batu-images/images/image%20(18).jpg',
                'title' => 'Professor',
                'sub_title' => null,
                'head_description' => 'Dr. Wafaa Ahmed Shaker is a dedicated academician and researcher in the field of health informatics. She brings extensive expertise and a passion for innovation to her role as a faculty member in the Health Informatics Department.',
                'career' => 'Throughout her career, Dr. Shaker has been actively involved in research projects addressing key challenges in health informatics, including health data management and interoperability.',
                'scientific_interests' => 'Her scientific interests include health information systems, clinical decision support, and healthcare data analytics.',
                'experience' => 'Dr. Shaker has taught a wide range of courses in health informatics at both the undergraduate and graduate levels. She is committed to providing students with a comprehensive understanding of health informatics principles and practices.',
                'word' => 'She is dedicated to advancing the field of health informatics through innovative research and education, with a focus on improving healthcare outcomes and patient care.',
                'certificates_title' => 'Ph.D. in Health Informatics',
                'certificates_description' => 'Dr. Shaker holds a Ph.D. in Health Informatics from a reputable institution, with her doctoral research focusing on health information systems interoperability.',
                'email' => 'wafaa@example.com',
                'cv' => 'https://linkdhub.github.io/batu-images/files/Wafaa%20online%20CV.pdf',
                'Researches_title' => 'Selected Researches',
                'Researches_description' => '1. "Clinical Decision Support Systems for Chronic Disease Management", Journal of Biomedical Informatics, 2019.',
                'user_id' => 1,
                'department_id' => 3,
                'faculty_id' => 1,
            ],
        ];

        static $index = 0;
        $staffMember = $staff[$index];
        $index = ($index + 1) % count($staff);

        return [
            'name' => $staffMember['name'],
            'image' => $staffMember['image'],
            'title' => $staffMember['title'],
            'sub_title' => $staffMember['sub_title'],
            'head_description' => $this->faker->paragraph,
            'certificates_title' => $this->faker->word,
            'certificates_description' => $this->faker->paragraph,
            'career' => $this->faker->paragraph,
            'word' => $this->faker->paragraph,
            'scientific_interests' => $this->faker->paragraph,
            'experience' => $this->faker->paragraph,
            'user_id' => $this->faker->numberBetween(1, 10),
            'department_id' => $this->faker->numberBetween(1, 6),
            'faculty_id' => $this->faker->numberBetween(1, 2),
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }
}
